### ISSUE TITLE
error when selenium driver trying to clock the contact

### ISSUE THREAD

**Issue by fumimuse** [shauryauppal/PyWhatsapp#2]
hi i get </span> is not clickable at point error, when the driver tried to click the name of contact on whatsapp account .
is there anyone having this  issue ?

**Comment by shauryauppal** [comment]
@fumimuse In the Contact list make changes as mentioned in the README Either you hardcode the contacts of your whatsapp or take as input at run time. 

If still the error exist do comment.

**Comment by shauryauppal** [comment]
@fumimuse 
`def input_contacts():
    global Contact
    # change it according to you.
    Contact = ['"Shaurya"', '"Shaurya new"']
    n = int(input('Enter number of Contacts to add->'))
    for i in range(0,n):
        inp = str(input("Enter contact name->"))
        inp = '"' + inp + '"'
        # print (inp)
        Contact.append(inp)
    # Print the new Contact list after additional input contacts
    print(Contact)
    print('')
`

**Comment by shauryauppal** [comment]
@fumimuse Status update?
Issue solved?
