### ISSUE TITLE
Save all Photos or # no. of photos from someones Whatsapp chat to Computer

### ISSUE THREAD

**Issue by shauryauppal** [shauryauppal/PyWhatsapp#24]

**Comment by Contrevien** [comment]
Please provide a description with a little example

**Comment by shauryauppal** [comment]
@Contrevien I want to do something similar to https://github.com/shauryauppal/code_for_fun/tree/master/WhatsApp_img_notes_extractor.

**Comment by shauryauppal** [comment]
This person connects the mobile phone to computer and then separates images. I want to get images directly through WhatsApp web. 
OR
For a particular contact name which I enter in contacts section, I just want to extract all the media attachment from our past conversation.

**Comment by adi0602** [comment]
Can we just start with saving all media files?

**Comment by shauryauppal** [comment]
@adi0602 You want to start this?

**Comment by adi0602** [comment]
Yes.

**Comment by shauryauppal** [comment]
@adi0602 Go head will wait for your PULL. Will merge today in the morning.
