### ISSUE TITLE
Contiguous Integration Implementation 

### ISSUE THREAD

**Issue by shauryauppal** [shauryauppal/PyWhatsapp#28]
I have no experience in writing unit test scripts. Found many resources for unit testing but for selenium, it isn't explained nicely anywhere. 

I want to add contiguous integration JENKINS or TRAVIS for this repo.

Help me with a good resource of unit testing for selenium in python. 

PRs are accepted for this.

**Comment by Pranay144** [comment]
i can add Travis CI for this repo... 
i will open a pull request soon!

**Comment by Pranay144** [comment]
#37
