### ISSUE TITLE
A separate text file for list of contact to send message

### ISSUE THREAD

**Issue by saikatghosh1998** [shauryauppal/PyWhatsapp#29]
If we can add a separate text file and add all the contact  in that file rather than inputting contacts manually in command line it will be more user friendly. In python we can iterate through the text  file and send message to the contacts.

**Comment by shauryauppal** [comment]
I will surely work on this. Thanks for your valuable feedback. Keep me updated if some issue occurs.

**Comment by Ghoul2077** [comment]
Please review PR #49 as this implements this feature

**Comment by shauryauppal** [comment]
PR #70 Done
