### ISSUE TITLE
add wait.until in the send_unsaved_contact

### ISSUE THREAD

**Issue by AksAman** [shauryauppal/PyWhatsapp#30]
The `send_message()` function works just fine, but when i try to send one to unsaved contact, sometime it fails if the xpath is not located (incase the contact is not opened by that time). I am trying to add similar `wait.untill...` in the unsaved method. But, the xpath is not locating it.

`x_arg = '//span[contains(@title,' + target + ')]' `
here i am using target as the mobile no. formatted as shown in whatsapp.

Please help

**Comment by shauryauppal** [comment]
![image](https://user-images.githubusercontent.com/20338789/66070677-6d561780-e56f-11e9-9d5a-36f33b8793d0.png)

**Comment by shauryauppal** [comment]
Whatsapp has changed it's UI and Options will fix it today.

**Comment by shauryauppal** [comment]
Issue Fixed
