### ISSUE TITLE
add bulk send contact

### ISSUE THREAD

**Issue by hananloser** [shauryauppal/PyWhatsapp#31]
please how to add bulk to send message

**Comment by shauryauppal** [comment]
Kindly elaborate the issue.

**Comment by pengyanbing84** [comment]
Automatically read the address book and send the information in batches?

**Comment by shauryauppal** [comment]
@pengyanbing84 We careful with the batch size. It should not be ideally 5 contacts batch then a wait of sometime else WhatsApp will ban you.
