### ISSUE TITLE
Sending messages to unsaved contacts getting on whatsApp 

### ISSUE THREAD

**Issue by patilanup246** [shauryauppal/PyWhatsapp#32]
from last 3 days sending msgs to unsaved contact not working.
https://web.whatsapp.com/send?phone=+91*********&source=&data=#

**Comment by shauryauppal** [comment]
You are using it in a wrong way

**Comment by shauryauppal** [comment]
Please read the README instructions again. +91 won't work. 91 will work. Don't use '+' @patilanup246

**Comment by patilanup246** [comment]
![image](https://user-images.githubusercontent.com/29545938/60386006-b9477b00-9aad-11e9-9834-04cf0e61e866.png)
I have try but getting same issue
