### ISSUE TITLE
Use normal chrome

### ISSUE THREAD

**Issue by MNCamargo** [shauryauppal/PyWhatsapp#33]
How to use a normal browser (chrome) to, avoid scan QR everytime?

**Comment by MNCamargo** [comment]
Solution:
from selenium.webdriver.chrome.options import Options

def whatsapp_login():
    global wait,browser,Link
    options = Options()
    options = webdriver.ChromeOptions()
    options.add_argument("user-data-dir=C:\\Users\\***USERNAME***\\AppData\\Local\\Google\\Chrome\\User Data\\Default")
    browser = webdriver.Chrome(options=options)

**Comment by ShauryaUppal-1Mg** [comment]
Can you send a PR for this?

**Comment by shauryauppal** [comment]
#41 #44

**Comment by shauryauppal** [comment]
@MNCamargo Instead of using Normal Chrome user data one can create own user_data folder again for this.
