### ISSUE TITLE
Add contacts contacts in bulk

### ISSUE THREAD

**Issue by pengyanbing84** [shauryauppal/PyWhatsapp#34]
How do I add contacts contacts in bulk?

**Comment by shauryauppal** [comment]
Add lot of contacts in the send list and after a batch (max. 4) msg add a time sleep with a random value. It should look human else whatsapp will ban you.

**Comment by shauryauppal** [comment]
Duplicate of #31

**Comment by Abhi-jeet1** [comment]
it is not sending a message to more than one unsaved contact..so can you take look on it
