### ISSUE TITLE
Integrate a ChatBot to this Project

### ISSUE THREAD

**Issue by shauryauppal** [shauryauppal/PyWhatsapp#45]
A Chatbot that can read the last send message and reply accordingly.

**Comment by anshratn1997** [comment]
Hi @shauryauppal ,
Will dialogflow chatbot work here?

**Comment by shauryauppal** [comment]
Any bot that could reply to a conversation. Reading previous and reply.

**Comment by shauryauppal** [comment]
Chatterbot will also work here.
