### ISSUE TITLE
Integration of Headless Driver

### ISSUE THREAD

**Issue by shauryauppal** [shauryauppal/PyWhatsapp#52]
Integrating Headless Chrome Driver in Pywhatsapp script.

**Comment by ashishnitinpatil** [comment]
The biggest issue I see here is circumventing the QR code scanning.

**Comment by shauryauppal** [comment]
@ashishnitinpatil i have fixed this in a eay like you have to scan qr code only once and next time you run the same code you don't need qr code that time headless can work.

**Comment by Exosylver** [comment]
How do I make it run in headless?

**Comment by shauryauppal** [comment]
Functionality Added but headless sometimes does not work if WhatsApp web takes a lot of time in the backend to open. Element Find timeouts
