### ISSUE TITLE
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 77

### ISSUE THREAD

**Issue by warifp** [shauryauppal/PyWhatsapp#56]
I have a problem "selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports **Chrome version 77**".
This is a same on version 77.
How to fix? i use Windows 10 64bit

**Comment by shauryauppal** [comment]
Your chrome driver and chrome web browser should be same.

Shaurya Uppal
