### ISSUE TITLE
Invalid to empty contacts

### ISSUE THREAD

**Issue by Nemo1710** [shauryauppal/PyWhatsapp#59]
Hi,

If you try to send to a known contact but you don't have chat with that contact it doesn't work

**Comment by ShauryaUppal-1Mg** [comment]
Know Issue cannot be solved.

**Comment by Nemo1710** [comment]
In that case, for contacts without chat I could send it as a uknown number, it could work, right?

**Comment by ShauryaUppal-1Mg** [comment]
Yes, it will work. With unsaved contact method, you can send message to any WhatsApp user.
