### ISSUE TITLE
Problem in whatsapp_login

### ISSUE THREAD

**Issue by gottfriedd** [shauryauppal/PyWhatsapp#62]
When calling this function - browser = webdriver.Chrome(options=chrome_options)
I am getting this error repeatedly - selenium.common.exceptions.WebDriverException: Message: unknown error: cannot create default profile directory.

How can I Solve this?

**Comment by shauryauppal** [comment]
Solved add executable_path

**Comment by shauryauppal** [comment]
browser = webdriver.Chrome(executable_path = './chromedriver',options=chrome_options)
