### ISSUE TITLE
Failed to send message Element not found

### ISSUE THREAD

**Issue by youmania83** [shauryauppal/PyWhatsapp#65]
I am getting following errors.

918368137724
Do you want to add more contacts(y/n)->n
Unsaved numbers entered list-> ['918368137724']

Press ENTER to continue...
Do you want to schedule your Message(yes/no):n
Would you like to send attachment(yes/no): n
Would you file to send a Document file(yes/no): n
SCAN YOUR QR CODE FOR WHATSAPP WEB
QR scanned
Sending message to 918368137724
Failed to send message
Task Completed

please help .

i think its unable to find element.

**Comment by varshil1** [comment]
I am facing the same problem for unsaved numbers only. Please help

**Comment by riflab** [comment]
@youmania83 you should write no instead of n

**Comment by shauryauppal** [comment]
@varshil1 and @youmania83 are you still facing an issue?
