### ISSUE TITLE
Not really an issue

### ISSUE THREAD

**Issue by gamegratis** [shauryauppal/PyWhatsapp#66]
Hello Shaurya! First I wanna thank you and say that we appreciate A LOT your time and efforts. 

My question isnt really an issue. I am concerned about WhatsApp blocking my number if I use a python module like yours to schedule messages. It is possible that WhatsApp tracks my "automated" messages and blocks my number?

I read that Chrome Plugins would be safer. I do know coding with python and Chrome Plugins but not enough to answer those questions. 

Again, thank you very much for your efforts on building this module, you are a life saver.

**Comment by twozero88** [comment]
If you use any whatsapp automation program that is not using whatsapp's official api, you are likely to get banned if you use it  a lot. More likely to get banned if you send same messages to many people in short interval and those people don't have your contact saved.

**Comment by shauryauppal** [comment]
If you plan to start with dev of chrome plugin @gamegratis or have already started and need support for contribution, I would love to chip in.
