### ISSUE TITLE
Please Help

### ISSUE THREAD

**Issue by HamzaQureshii** [shauryauppal/PyWhatsapp#89]
![Screenshot (745)](https://user-images.githubusercontent.com/24480162/154866567-2aa288a7-0536-4959-b59b-cc3eca6cee92.png)

**Comment by shauryauppal** [comment]
This is a vhrome driver issue not application level issue. Try to run chrome driver for a small program then shift to this code base.

**Comment by HamzaQureshii** [comment]
app runs but wont redirect to whatsapp website web.whatsapp for further sending messages stops at chrome browser opened and wont go further
